Niels folder download
genomescan/gsport pull request #1
Opened 2020-07-15 10:22 UTC by nielsdw

This should be merged when also the portal itself is updated. Endpoints used by this version are not compatible with the current portal and vice vera. We are going to have to include a note/reminder in the 'Project finished' emails we send to our customers.

2020-07-17 14:55 UTC, emiel requested changes
I played around with this today and left some comments. I'm out of time now but will share what I have so far. I'll pick it up again on Monday.

2020-07-17 14:55 UTC, emiel commented on gsport.py
> +-H --host [host], default: https://portal.genomescan.nl
This would break compatibility and seems unexpected. Let's not create more confusion by changing the meaning of options.

The value given is not only the host but also the scheme (`https`). A better name would be  `-u, --uri` or something similar. Alternatively you could split up the options as `--ssl` `--no-ssl` and host and then build the URI yourself. Though my preference would be just to use URI.

2020-07-17 14:55 UTC, emiel commented on gsport.py
> +-t --threads [n] allow n concurrent threads (works only on Linux)
Given we're not using threads here (only multiprocessing) threads is a bit of a misnomer here. Python 3 now has a module `concurrent.futures` which abstracts nicely over processes and threads and would fit nicely here. Not saying we do that now but is a good candidate. Anyway you could use `workers` instead of threads as it maps nicely to either processes or threads.

2020-07-17 14:55 UTC, emiel commented on gsport.py
> +-t --threads [n] allow n concurrent threads (works only on Linux)
BTW. Why Linux only?

2020-07-17 14:55 UTC, emiel commented on gsport.py
> +-h --help prints this help
After playing with it a little I found all the flags quite confusing. We could start breaking it up a bit into subcommands (see `argparse`). Let's think about how to classify and pair up all these flags, i.e. which are global and which are specific to a certain operation.

* `gsport ls <project> <prefix>`
* `gsport get <project> `
* `gsport getall`
* etc...

2020-07-17 14:55 UTC, emiel commented on gsport.py
> +                                        "clear-cookies", "help", "dirs", "cd=", "recursive"])
I believe there is a comma missing before "clear-cookies". Python will then simply concat the strings.

2020-07-17 14:55 UTC, emiel commented on gsport.py
> +        self.cookies = http.cookiejar.MozillaCookieJar(filename=os.path.join(str(Path.home()), '.gs_cookies.txt'))
```suggestion
        self.cookies = http.cookiejar.MozillaCookieJar(filename=str(Path(Path.home(), '.gs_cookies.txt'))
```
Just want to point out you can join paths using pathlib. Both will work.

2020-07-17 14:55 UTC, emiel commented on gsport.py
> +            # print("\rDownloading", fname, '                                     ')
Let's get rid of commented out code.

2020-07-17 14:55 UTC, emiel commented on gsport.py
> +                self.options.dir = '/'.join(self.options.dir.split('/')[:-1])
Downloading a file sets an option?

2020-07-17 14:55 UTC, emiel commented on gsport.py
> +-t --threads [n] allow n concurrent threads (works only on Linux)
I also noticed that the default is a single thread. User's won't benefit from additional work processes unless they bump up the number of workers themselves using the parameter. A more sensible default would be to use number of cores available on the system (Python has various ways to get this).

2020-07-21 09:17 UTC, nielsdw commented on gsport.py
> +-H --host [host], default: https://portal.genomescan.nl
Customers don't use this option. -h (lower case) is more common use for --help.

2020-07-21 09:21 UTC, nielsdw commented on gsport.py
> +-t --threads [n] allow n concurrent threads (works only on Linux)
I put self.threads = os.cpu_count() as default and in help:

-t --workers [n] allow n concurrent workers (defaults to number of logical cpu cores) (works only on Linux)

2020-07-21 09:21 UTC, nielsdw commented on gsport.py
> +-h --help prints this help
Future work, if ever (customers get used to the current flag system)

2020-07-21 09:22 UTC, nielsdw commented on gsport.py
> +-t --threads [n] allow n concurrent threads (works only on Linux)
Try it in Windows... Perhaps in the future, we need a different concurrency lib.

2020-07-21 09:23 UTC, nielsdw commented on gsport.py
> +                self.options.dir = '/'.join(self.options.dir.split('/')[:-1])
It modifies it :P

2020-07-21 19:08 UTC, nielsdw commented
I changed the views from POST to GET, like preferred.

2020-07-23 12:41 UTC, merged